CREATE TABLE ESB_KFTC_FTI_KEY
(
    ORG_CODE VARCHAR2(3) NOT NULL,
    GEN_DATE VARCHAR2(8),
    PRIVATE_KEY VARCHAR2(2000),
    PUBLIC_KEY VARCHAR2(500),
    LAST_UPDATE_DT VARCHAR2(17),
    CONSTRAINT ESB_KFTC_KEYS PRIMARY KEY ("ORG_CODE")
);

CREATE TABLE ESB_KFTC_FTI_OTK
(

    ORG_CODE       VARCHAR2(3) NOT NULL,
    GEN_DATE       VARCHAR2(8) NOT NULL,
    OTK            VARCHAR2(50),
    LAST_UPDATE_DT VARCHAR2(17),
    CONSTRAINT ESB_KFTC_OTK PRIMARY KEY ("GEN_DATE", "ORG_CODE")
);

COMMENT ON TABLE ESB_KFTC_FTI_KEY IS '금융결제원 금융거래정보 키 관리 테이블';
COMMENT ON COLUMN ESB_KFTC_FTI_KEY.ORG_CODE IS '기관 코드';
COMMENT ON COLUMN ESB_KFTC_FTI_KEY.GEN_DATE IS '생성일';
COMMENT ON COLUMN ESB_KFTC_FTI_KEY.PRIVATE_KEY IS '개인키을 base64 String으로 변환한 값';
COMMENT ON COLUMN ESB_KFTC_FTI_KEY.PUBLIC_KEY IS '공개키을 base64 String으로 변환한 값';
COMMENT ON COLUMN ESB_KFTC_FTI_KEY.LAST_UPDATE_DT IS '키 최종갱신시간';

COMMENT ON TABLE ESB_KFTC_FTI_OTK IS '금융결제원 금융거래정보 One Time Key 관리 테이블';
COMMENT ON COLUMN ESB_KFTC_FTI_OTK.ORG_CODE IS '기관 코드';
COMMENT ON COLUMN ESB_KFTC_FTI_OTK.GEN_DATE IS '생성일';
COMMENT ON COLUMN ESB_KFTC_FTI_OTK.OTK IS 'One Time Key를 base64 String으로 변환한 값';
COMMENT ON COLUMN ESB_KFTC_FTI_OTK.LAST_UPDATE_DT IS '키 최종갱신시간';