server:
  port: 28000

tcp:
  suhyup-bank:
    host: 127.0.0.1
    port: 5555
    client-timeout-sec: 10

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  main:
    allow-bean-definition-overriding: true
