server:
  port: 8080

tcp:
  suhyup-bank:
    host: 127.0.0.1
    port: 9999

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  main:
    allow-bean-definition-overriding: true
