server:
  port: 28000

tcp:
  server:
    enabled: true
    bind-port: 9999
  client:
    host: 127.0.0.1
    port: 5555
    client-timeout-sec: 10

web:
  app-service:
    url: http://localhost:1080/suhyup/app-api

interface:
  spec:
    enable-json-file: true

mockserver:
  enabled: true
  port: 1080

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  main:
    allow-bean-definition-overriding: true
