@startuml
abstract class mb.fw.atb.strategy.ATBStrategy {
# IFConfig config
# AdaptorConfigBean adaptorConfigBean
# IFTPClient client
# ObjectMapper objectMapper
# XmlMapper xmlMapper
# JmsTemplate jmsTemplate
+ {abstract}Specifications specifications()
+ {abstract}OnSignalInfo onSignal(IFContext,String,String)
+ {abstract}OnSignalInfo onSignalRetry(IFContext,String,String,Map<String,String>)
+ {abstract}Object onMessageData(IFContext,String,String,Object,Map<String,String>)
+ {abstract}void onMessageResult(IFContext,String,String,String,String,String,Map<String,String>)
+ void startLogging(IFContext,String,String,String,long)
+ void endLogging(IFContext,String,long,String,String,String)
}


class mb.fw.atb.strategy.batch.FileMoveStrategy {
~ String separator
- JmsTemplate jmsTemplate
~ ObjectMapper om
+ Specifications specifications()
+ OnSignalInfo onSignal(IFContext,String,String)
+ OnSignalInfo onSignalRetry(IFContext,String,String,Map<String,String>)
+ Object onMessageData(IFContext,String,String,Object,Map<String,String>)
+ void onMessageResult(IFContext,String,String,String,String,String,Map<String,String>)
- {static} void generateFileMessage(IFContext,String,List<Path>,FileMessage)
}



class mb.fw.atb.strategy.batch.StandardFTDBatch {
~ DBTransactionService dbTransactionService
~ ObjectMapper mapper
+ Specifications specifications()
+ OnSignalInfo onSignal(IFContext,String,String)
- FileMessage processFileToDB(IFContext,String,String,List<Path>,boolean)
+ OnSignalInfo onSignalRetry(IFContext,String,String,Map<String,String>)
+ Object onMessageData(IFContext,String,String,Object,Map<String,String>)
+ void onMessageResult(IFContext,String,String,String,String,String,Map<String,String>)
- {static} void generateFileMessage(IFContext,String,List<Path>,FileMessage)
}






 FileMoveStrategy -up-> ATBStrategy
 StandardFTDBatch -up-> ATBStrategy
@enduml