POST http://clupine.duckdns.org:24220/na-api/IF_VIRACC_OUT_REQ_001
Content-Type: application/json

{
  "data" : "ICAgICAgICAgICAgVkFTMkJLQ0EyNTMgICBCS0NBMDExICAgMTA2MTMyMDE5OTYwMzAwMDE0ODMxMTAyMDAzMDAwMDExNDYyMDI0MDQxNjEzMjAxOTAwMDAyMjgyMTAwMDExQ0IwMDAwMTMxNzcwICAgICAgICAgMjAyNDA0MTYwMDAwMTkgICAgICAgICAgICAgICAxMjEyMDAwMDAwMDQ0MDAwMCAwMDAwMDAwMDAwMDAwMTI0ODIxsei5zrHUIChTSCkgICAgICAgICAgICAgICAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDA3OTAwNDExMzc1NzA4MyAgMTMyMDE5MjAyNDA0MTYgICAgICAgICAgICAgMDAwMDg5WTAxMTAxMjAxMjQ4MjEgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA="
}

